import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Kevin Mathew | AR/VR Developer Portfolio",
  description: "Welcome to Kevin Mathew's AR/VR Developer and UX Designer portfolio showcasing innovative projects in humanoid robotics, autonomous systems, and immersive experiences.",
  keywords: [
    "ar-vr-developer",
    "unity-developer",
    "ux-ui-designer",
    "humanoid-robotics",
    "autonomous-systems",
    "cybersecurity",
    "kevin-mathew",
    "immersive-experiences",
    "3d-modeling",
    "ar-filters",
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "postcss",
    "react-dom",
    "tailwindcss",
    "ui/ux",
    "js",
    "javascript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Kevin Mathew",
    url: "https://github.com/kevinmathew47",
  },
} as const;
